"""empty message

Revision ID: ffb549914831
Revises: ec9f39f24d1c
Create Date: 2020-07-21 14:02:56.096113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb549914831'
down_revision = 'ec9f39f24d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_artist', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_artist', 'start_date')
    # ### end Alembic commands ###
